route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 120s
  group_wait: 30s
  receiver: 'default_channel' # default/fallback request handler
  routes:
    - receiver: 'default_channel'

receivers:
  - name: 'default_channel'
    webhook_configs:
      - url: 'http://prometheus-msteam:2000/warning_channel'
      - url: 'http://alertmanager-bot:8080'
        send_resolved: true

        #- name: 'alertmananger-bot'
  #  webhook_configs:
          #  - send_resolved: true
    #    url: 'http://alertmanager-bot:8080'

        #- name: 'prometheus-msteam'
        #  webhook_configs:
          #  - send_resolved: true
    #    url: 'http://prometheus-msteam:2000'
